version: "2"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
     - "443:443"
     - "8443:443"
    links:
    - database
    volumes:
     - .:/var/www
     - ./fullchain.pem:/etc/ssl/certs/fullchain.pem
     - ./privkey.pem:/etc/ssl/private/privkey.pem
  database:
    image: mysql
    ports:
     - 3306:3306
    command:
     --default-authentication-plugin=mysql_native_password
    volumes:
     - ./.data/db:/var/lib/mysql
     - ./.docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
     - MYSQL_ROOT_PASSWORD=testpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8081:80
    environment:
      - PMA_HOST=database